---
title: "hw01"
author: "Brendan Zimmer"
date: "9/22/2021"
output: github_document
---
```{r}
library(rvest)
library(stringr)
```


```{r}
staff_data <- read.csv(url("https://guide.wisc.edu/faculty/"), row.names = NULL)
staff_data
```
```{r}
staff_data <- read_html("https://guide.wisc.edu/faculty/")

```

```{r}
staff_names <- html_nodes(staff_data, "p")
staff_full <- strsplit(toString(staff_names), "<p>")[[1]]
head(staff_full)
```
```{r}
#gsub("<br>", " ", staff_full)
staff_full <- str_replace_all(staff_full, "<br>", "-")
staff_full <- str_replace_all(staff_full, "</p>", " ")
head(staff_full)
```


```{r}
staff_full <- 
```

```{r}
df = read.delim("2020HwyBridgesDelimitedAllStates.txt", header = TRUE, sep = ",")
head(df)
```
```{r}
library(dplyr)
library(ggplot2)

```


```{r}
new_df <- df %>% select(STATE_CODE_001, MAINTENANCE_021, DESIGN_LOAD_031, RAILINGS_036A, YEAR_RECONSTRUCTED_106, BRIDGE_CONDITION, YEAR_BUILT_027)

head(new_df)
```

```{r}
numdf <- as.data.frame(new_df)
numdf$BRIDGE_CONDITION <- gsub('G', '3', numdf$BRIDGE_CONDITION)
numdf$BRIDGE_CONDITION <- gsub('P', '1', numdf$BRIDGE_CONDITION)
numdf$BRIDGE_CONDITION <- gsub('F', '2', numdf$BRIDGE_CONDITION)
```


```{r}
numdf <- numdf %>% filter(STATE_CODE_001 == "55")
  #mutate(State_Code = STATE_CODE_001, Maintenance = MAINTENANCE_021)

```

```{r}
colnames(numdf) <- c("State Code", "Maintenance", "Design Load", "Railings", "Year Reconstructed", "Bridge Condition", "Year Built")

numdf <- as.data.frame(apply(numdf, 2, as.numeric))

typeof(data_num[1, 1])
```


```{r}
new_df %>% ggplot(aes("Year Built", "Bridge Condition"))

```